services:
  mongodb:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    env_file: ./auth-service/.env
    ports: ["4000:4000"]
    depends_on:
      - mongodb

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    ports: ["4001:4001"]
    depends_on:
      - mongodb
      - auth-service

  frontend:
    build: ./frontend
    ports: ["3000:80"]
    depends_on:
      - auth-service
      - post-service

  notification-service:
    build: ./notification-service
    env_file: ./notification-service/.env
    depends_on:
      - mongodb
    environment:
      - PORT=4002
      - MONGODB_URI=mongodb://mongo:27017/notifications
      - SERVICE_KEY=super-secret-service-key-CHANGE_THIS
      - AUTH_SERVICE_URL=http://auth-service:4000
    ports:
      - "4002:4002"

volumes:
  mongo_data: