services:
  mongodb:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    env_file: ./auth-service/.env
    ports: ["4000:4000"]
    depends_on:
      - mongodb

  post-service:
    build: ./post-service
    env_file: ./post-service/.env
    ports: ["4001:4001"]
    depends_on:
      - mongodb
      - auth-service

  message-service:
    build: ./message-service
    env_file: ./message-service/.env
    ports: ["4002:4002"]
    depends_on:
      - mongodb
      - auth-service

  frontend:
    build: ./frontend
    ports: ["3000:80"]
    depends_on:
      - auth-service
      - post-service
      - message-service

volumes:
  mongo_data:
